name: Check, build, and push image

on: [push, pull_request]

env:
  cache-version: v1

jobs:
  r-build-and-check:
    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:devel

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: TRUE
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CRAN: https://packagemanager.posit.co/cran/__linux__/jammy/latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Query dependencies and update old packages
        run: |
          install.packages('remotes')
          dir.create(".github")
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}
        
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/R/site-library
          key: ${{ env.cache-version }}-${{ runner.os }}-r-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ env.cache-version }}-${{ runner.os }}-r-

      - name: Install dependencies
        run: |
          BiocManager::repositories()
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories())
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      # - name: Check
      #   env:
      #     _R_CHECK_CRAN_INCOMING_REMOTE_: false
      #   run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning", check_dir = "check")
      #   shell: Rscript {0}

      - name: Build pkgdown
        run: |
           PATH=$PATH:$HOME/bin/ Rscript -e 'BiocManager::install(c("knitr", "rmarkdown", "pkgdown")); pkgdown::build_site(".")'

      # deploy needs rsync? Seems so.
      - name: Install deploy dependencies
        run: |
          apt-get update
          apt-get -y install rsync

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
